apiVersion: v1
kind: Pod
metadata:
  name: servicio-d-pod
  labels:
    app: servicio-d
spec:
  containers:
    - name: servicio-d-container
      image: ervincaravaliibarra/bebidas:latest
      ports:
        - containerPort: 7000
  tolerations:
    - key: "environment"
      operator: "Equal"
      value: "production"
      effect: "NoSchedule"

---

apiVersion: v1
kind: Service
metadata:
  name: servicio-d-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 7000
      protocol: TCP
  selector:
    app: servicio-d