apiVersion: v1
kind: Pod
metadata:
  name: apigw-pod
  labels:
    app: apigw
spec:
  containers:
    - name: apigw-container
      image: yenreh/apigw:latest
      ports:
        - containerPort: 4000

---

apiVersion: v1
kind: Service
metadata:
  name: apigw-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
  selector:
    app: apigw