apiVersion: v1
kind: Pod
metadata:
  name: servicio-b-pod
  labels:
    app: servicio-b
spec:
  containers:
    - name: servicio-b-container
      image: yenreh/servicio-b:latest
      ports:
        - containerPort: 3002
  tolerations:
    - key: "environment"
      operator: "Equal"
      value: "production"
      effect: "NoSchedule"

---

apiVersion: v1
kind: Service
metadata:
  name: servicio-b-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3002
      protocol: TCP
  selector:
    app: servicio-b