apiVersion: v1
kind: Pod
metadata:
  name: servicio-f-pod
  labels:
    app: servicio-f
spec:
  containers:
    - name: servicio-f-container
      image: ervincaravaliibarra/dulces:latest
      ports:
        - containerPort: 6000
  tolerations:
    - key: "environment"
      operator: "Equal"
      value: "production"
      effect: "NoSchedule"

---

apiVersion: v1
kind: Service
metadata:
  name: servicio-f-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 6000
      protocol: TCP
  selector:
    app: servicio-f