apiVersion: v1
kind: Pod
metadata:
  name: authservice-pod
  labels:
    app: authservice
spec:
  containers:
    - name: authservice-container
      image: yenreh/authservice:latest
      ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: authservice-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: authservice

---
